version: 2

models:
  - name: distinct_Manufacturer
    columns:
      - name: manufacturer
        tests:
          - not_null
          - unique
  - name: class_details
    columns:
      - name: starship_class
        tests:
          - not_null
          - unique
      - name: selling_count
        tests:
          - not_null
  - name: manufacturer_sellings
    columns:
      - name: manufacturer1
        tests:
          - not_null
  - name: starship_details
    columns:
      - name: starship_name
        tests:
          - not_null
          - unique

      - name: starship_class
        tests:
          - not_null
  - name: starship_model_classification
    columns:
      - name: starship_class
        tests:
          - not_null
          - unique
      - name: starship_group
        tests:
          - accepted_values:
              values: ['small starships', 'medium starships', 'large starships','null']
      - name: speed_classification
        tests:
          - accepted_values:
              values: ['high speed', 'medium speed', 'low speed','null']