name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # If needed

      - name: List Files and Directories (Debugging - Highly Recommended)
        run: ls -alR  # or 'dir /s' on Windows

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest psycopg2 pandas scikit-learn dbt-core
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Set up PostgreSQL
        uses: ankane/setup-postgres@v1
        with:
          postgres-version: '14'
          db-name: 'test_db'
          db-user: 'admin'
          db-pass: 'admin'

      - name: Run API Caller
        run: python APIcaller.py  # No cd or working-directory needed!
        env: # Set environment variables for DB connection
          DB_HOST: localhost
          DB_NAME: test_db
          DB_USER: admin
          DB_PASS: admin

      - name: Run DBT Models
        run: dbt run  # No cd or working-directory needed!

      - name: Run Train Classifier
        run: python Train_Classifier.py  # No cd or working-directory needed!
        env: # Set environment variables for DB connection
          DB_HOST: localhost
          DB_NAME: test_db
          DB_USER: admin
          DB_PASS: admin

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: pytest
        
        
 
