name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create and Activate Virtual Environment & Install Dependencies (ONCE)
        run: |
          cd ${{ github.workspace }}/retail_pg  # Go to project directory
          python -m venv .venv  # Create virtual environment
          .venv\Scripts\Activate.ps1  # Activate it
          pip install --upgrade pip
          pip install requests psycopg2 flake8 pytest dbt-core dbt-postgres pandas scikit-learn # Install ALL dependencies at once
          if (Test-Path requirements.txt) { pip install -r requirements.txt } # Install from requirements.txt if available

      - name: Set up PostgreSQL
        uses: ankane/setup-postgres@v1
        with:
          postgres-version: '14'

      - name: Create Database and User
        shell: pwsh
        run: |
          # ... (database and user creation - same as before)

      - name: Run API Caller
        run: |
          cd ${{ github.workspace }}/retail_pg
          .venv\Scripts\Activate.ps1  # Activate the virtual environment (REUSE)
          python APIcaller.py
        env:
          # ... (environment variables)

      - name: Run DBT Models and Tests
        run: |
          cd ${{ github.workspace }}/retail_pg
          .venv\Scripts\Activate.ps1  # Activate the virtual environment (REUSE)
          # ... (dbt commands - same as before)
        env:
          # ... (environment variables)

      - name: Run Train Classifier
        run: |
          cd ${{ github.workspace }}/retail_pg
          .venv\Scripts\Activate.ps1  # Activate the virtual environment (REUSE)
          python Train_Classifier.py
        env:
          # ... (environment variables)

      - name: Lint with flake8
        run: |
          cd ${{ github.workspace }}/retail_pg
          .venv\Scripts\Activate.ps1  # Activate the virtual environment (REUSE)
          # ... (flake8 commands - same as before)

      - name: Test with pytest
        run: |
          cd ${{ github.workspace }}/retail_pg
          .venv\Scripts\Activate.ps1  # Activate the virtual environment (REUSE)
          pytest
